# Generated by Django 5.0.3 on 2024-04-12 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('etage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Materiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('smartphone', 'Smartphone'), ('tablette', 'Tablette'), ('ecran', 'Écran'), ('video_projecteur', 'Vidéo Projecteur'), ('pointeur_laser', 'Pointeur Laser')], max_length=20)),
                ('description', models.TextField()),
                ('proprietaire', models.CharField(default="L'école", max_length=100)),
                ('accessoires', models.TextField()),
                ('date_acquisition', models.DateField()),
                ('possesseur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels_possedes', to='gestion_materiel.enseignant')),
                ('salle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='gestion_materiel.salle')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField()),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_reelle', models.DateField(blank=True, null=True)),
                ('emprunteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='gestion_materiel.enseignant')),
                ('materiel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='gestion_materiel.materiel')),
            ],
        ),
    ]
