# Generated by Django 5.0.3 on 2024-04-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_materiel', '0002_alter_materiel_proprietaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='proprietaire',
            field=models.CharField(default="L'école", max_length=100),
        ),
    ]
