# Generated by Django 5.0.3 on 2024-04-12 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_materiel', '0007_alter_materiel_possesseur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiel',
            name='salle',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiels', to='gestion_materiel.salle'),
        ),
    ]
